# Generated by Django 4.2 on 2023-06-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_compartments_product_compartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compartment',
        ),
        migrations.AddField(
            model_name='product',
            name='coLllection',
            field=models.CharField(choices=[('Best Sellers', 'Best Sellers'), ('New Arrivals', 'New Arrivals'), ('Box Sets', 'Box Sets'), ('Todays Deal ', 'Todays Deal')], default=1, max_length=200),
        ),
    ]
