# Generated by Django 4.2 on 2023-06-08 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_compartment_product_colllection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='coLllection',
        ),
        migrations.AddField(
            model_name='product',
            name='collections',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.collections'),
            preserve_default=False,
        ),
    ]
