# Generated by Django 4.2 on 2023-07-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('0 TO 200', '0 TO 200'), ('0 TO 400', '0 TO 400'), ('0 TO 600', '0 TO 600'), ('0 TO 800', '0 TO 800'), ('0 TO 1000', '0 TO 1000'), ('0 TO 2000', '0 TO 2000')], max_length=60),
        ),
    ]
